version: "3"
services:
  side_users_db:
    container_name: side_users_db
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=b1sm1llah
      - POSTGRES_USER=root
      - POSTGRES_DB=side_db
    volumes:
      - $HOME/.pgsql/side/db:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: "always"
    networks:
      - side_default
  side_users_service:
    container_name: side_users_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    volumes:
      - .:/users_service/
    env_file:
      - ./.env
    links:
      - "side_users_db:side_users_db"
    depends_on:
      - side_users_db
    command: ["./wait-for-it.sh"]
    restart: "no"
    networks:
      - side_default
volumes:
  side_users_db:
networks:
  side_default:
    external: true
