apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: side_service-frontend
  labels:
    app: side_service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: side_service
        tier: frontend
    spec:
      containers:
        - name: side_service-app
          # Replace [GCLOUD_PROJECT] with your project ID or use `make template`.
          image: gcr.io/side_service-service/side_service-service:v0.1
          # This setting makes nodes pull the docker image every time before
          # starting the pod. This is useful when debugging, but should be turned
          # off in production.
          imagePullPolicy: Always
          # The PROCESSES environment variable is used by Honcho in the
          # Dockerfile's CMD to control which processes are started. In this
          # case, only the bookshelf process is needed.
          env:
            - name: PROCESSES
              value: side_service
          # The bookshelf process listens on port 8080 for web traffic by default.
          ports:
            - name: http-server
              containerPort: 8080
