apiVersion: v1
kind: Service
metadata:
  name: side_service-frontend
  labels:
    app: side_service
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: side_service
    tier: frontend