"""empty message

Revision ID: 2aba51f98dff
Revises: 4f7fabfb6d6f
Create Date: 2019-10-14 10:45:12.778172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aba51f98dff'
down_revision = '4f7fabfb6d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tb_desa', ['kode_desa'])
    op.create_unique_constraint(None, 'tb_kab', ['kode_kab'])
    op.create_foreign_key(None, 'tb_kab', 'tb_prov', ['kode_prov'], ['kode_prov'])
    op.create_unique_constraint(None, 'tb_kec', ['kode_kec'])
    op.create_unique_constraint(None, 'tb_prov', ['kode_prov'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_prov', type_='unique')
    op.drop_constraint(None, 'tb_kec', type_='unique')
    op.drop_constraint(None, 'tb_kab', type_='foreignkey')
    op.drop_constraint(None, 'tb_kab', type_='unique')
    op.drop_constraint(None, 'tb_desa', type_='unique')
    # ### end Alembic commands ###
