"""empty message

Revision ID: 4f7fabfb6d6f
Revises: 
Create Date: 2019-10-14 10:10:10.671267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7fabfb6d6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_kab',
    sa.Column('kode_kab', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('kode_prov', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('kode_kab'),
    sa.UniqueConstraint('kode_kab')
    )
    op.create_table('tb_prov',
    sa.Column('kode_prov', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('kode_prov'),
    sa.UniqueConstraint('kode_prov')
    )
    op.create_table('tb_kec',
    sa.Column('kode_kec', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('kode_kab', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['kode_kab'], ['tb_kab.kode_kab'], ),
    sa.PrimaryKeyConstraint('kode_kec'),
    sa.UniqueConstraint('kode_kec')
    )
    op.create_table('tb_desa',
    sa.Column('kode_desa', sa.String(length=40), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('kode_kec', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['kode_kec'], ['tb_kec.kode_kec'], ),
    sa.PrimaryKeyConstraint('kode_desa'),
    sa.UniqueConstraint('kode_desa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_desa')
    op.drop_table('tb_kec')
    op.drop_table('tb_prov')
    op.drop_table('tb_kab')
    # ### end Alembic commands ###
